# Generated by Django 5.0.7 on 2024-08-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('main_dish', models.CharField(max_length=50)),
                ('side_dish', models.CharField(max_length=50)),
                ('desert', models.CharField(max_length=50)),
                ('type_of_meal', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('S', 'Snack')], max_length=1)),
            ],
        ),
    ]
