# Generated by Django 5.0.7 on 2024-08-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='desert',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='meal',
            name='main_dish',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='meal',
            name='side_dish',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='meal',
            name='type_of_meal',
            field=models.CharField(blank=True, choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('S', 'Snack')], max_length=1),
        ),
    ]
